### ISSUE TITLE
DesignerExports.reload 会导致页面拽拖产生两个元素。

### ISSUE THREAD

**Issue by StringKe** [hlerenow/chameleon#11]
https://hlerenow.github.io/chameleon/

1. 打开 demo
2. 点击右上角的 Refresh Page
3. 拽拖一个新的元素到页面上

**Comment by hlerenow** [comment]
已修复：
https://github.com/hlerenow/chameleon/commit/1507549632c3c6e09d8555fd0286fcc72855c358
