### ISSUE TITLE
Setter 设置 DefaultValue 无效。

### ISSUE THREAD

**Issue by StringKe** [hlerenow/chameleon#14]
https://github.com/hlerenow/chameleon/blob/master/packages/model/src/types/material.ts#L216

物料定义的地方有这个key，在 CustomSchemaForm 中没有找到对应的设置。

另外发现个小问题
https://github.com/hlerenow/chameleon/blob/master/packages/engine/src/component/CustomSchemaForm/index.tsx#L72

这里似乎要处理 property.content 的内容，但是没处理？

**Comment by hlerenow** [comment]
property.content  处理漏了，等我抽时间看看怎么处理。

**Comment by hlerenow** [comment]
DefaultValue 目前没有使用，后面会移除。因为 一个 prop 可能有多个设置器，所以对应的默认值放在了 setter 中的 initialValue 属性配置，这样不同的 setter 就可以用于不同的默认值类型。

https://github.com/hlerenow/chameleon/blob/b7ebb595e1ebdc529c5da975ae34e6b1100444aa/packages/model/src/types/material.ts#L164

**Comment by StringKe** [comment]
那么这样 https://github.com/hlerenow/chameleon/blob/b7ebb595e1ebdc529c5da975ae34e6b1100444aa/packages/engine/src/material/innerMaterial.ts#L48 字符串写的方式就不支持默认值了么？

**Comment by hlerenow** [comment]
支持，只要 setter 实现了对 initialValue 的处理就行，这里是简写。可以传递对象，参考：
https://github.com/hlerenow/chameleon/blob/b7ebb595e1ebdc529c5da975ae34e6b1100444aa/packages/model/src/types/material.ts#LL160C21-L160C21
`
setters: [{
    componentName: 'StringSetter',
    initialValue: ''
}]
`

**Comment by StringKe** [comment]
对比 ` setters: ['StringSetter', 'ExpressionSetter'], ` 还是要写比较多的内容，先用 initialValue 了。

**Comment by hlerenow** [comment]
其实这里的 initalValue  可以被默认值的组件 schema 片段替代。直接 在 schema 中预填写 对应props 的 value，也能实现自动填入默认值的功能，更方便些

**Comment by hlerenow** [comment]
参考：https://github.com/hlerenow/chameleon/blob/b7ebb595e1ebdc529c5da975ae34e6b1100444aa/packages/demo-page/src/material/native.ts#LL22C9-L22C17

**Comment by StringKe** [comment]
我测试了一下 String Boolean 这两个 Setter 配置 initalValue 是无效的。

**Comment by hlerenow** [comment]
刚看了一下，目前只对 shape 和 array，其他的暂时还没实现。后面处理下

**Comment by hlerenow** [comment]
基础 setter 实现 initalValue 配置

**Comment by KurumiRin** [comment]
<img width="673" alt="image" src="https://github.com/hlerenow/chameleon/assets/52448921/80866468-947d-4c50-af84-9bebf7ed67af">
ArraySetter似乎只有内部item的initalValue可以生效，对ArraySetter本身给初始值是没有生效的

**Comment by hlerenow** [comment]
> <img alt="image" width="673" src="https://user-images.githubusercontent.com/52448921/245988299-80866468-947d-4c50-af84-9bebf7ed67af.png"> ArraySetter似乎只有内部item的initalValue可以生效，对ArraySetter本身给初始值是没有生效的

master 更新功能，之前 initlaValue 没有完全实现，等待发包更新。

**Comment by hlerenow** [comment]
> 我测试了一下 String Boolean 这两个 Setter 配置 initalValue 是无效的。

master 已更新功能，之前 initlaValue 没有完全实现，等待发包更新。

**Comment by KurumiRin** [comment]
> > 我测试了一下 String Boolean 这两个 Setter 配置 initalValue 是无效的。
> 
> master 已更新功能，之前 initlaValue 没有完全实现，等待发包更新。

<img width="611" alt="image" src="https://github.com/hlerenow/chameleon/assets/52448921/a99fd5ee-249e-4d08-9612-3f143a8cb44d">
<img width="1472" alt="image" src="https://github.com/hlerenow/chameleon/assets/52448921/ddfaf51e-c333-4b0b-9c78-da783d7c36ac">
initialValue在stringSetter上可以生效了，但是没有和schema同步，input内容改变时schema也没有修改

**Comment by KurumiRin** [comment]
stringsetter现在可以生效了，但是默认值没有在初始化时写入到schema中
<img width="1511" alt="image" src="https://github.com/hlerenow/chameleon/assets/52448921/f2b5fd9a-e483-4ac2-b4a3-f57cf1151323">

**Comment by hlerenow** [comment]
> stringsetter现在可以生效了，但是默认值没有在初始化时写入到schema中 <img alt="image" width="1511" src="https://user-images.githubusercontent.com/52448921/246036317-f2b5fd9a-e483-4ac2-b4a3-f57cf1151323.png">

这里其实有个逻辑问题需要考虑下，设置器的 默认值只是表示 设置器的默认值，并不会直接写到 schema 中。

场景1: render 渲染了一个组件但是根本没有打开 对应元素的设置器面板，这个时候是无法同步到 schema 中的，即使可以同步也不知道应该用那个值同步，所以必须用户主动修改，才能去更新 schema。initialValue 只是辅助设置器设置初始值的操作，比如新增了一个元素，这个时候会使用 initalValue 去填充，在复杂的数据结构下。比如是一个object，但是如果没有配置 initalValue ，这个时候设置器不知道应该填入什么数据，如果传入一个 空字符串，会导致接收组件内部对于props 的访问异常

如果想设置 schema 的默认值应该在 snippets 中的片段直接配置，组件被拖入之后会携带所的默认配置到 schema 中。
