### ISSUE TITLE
文件缺失

### ISSUE THREAD

**Issue by nickyzhang-fe** [hlerenow/chameleon#28]
![image](https://github.com/hlerenow/chameleon/assets/10348941/a5db3b0d-46ec-442c-b4c9-76fa4c0beddf)

packages/build-script/lib/ 下的文件没上传，能麻烦上传一下吗

**Comment by hlerenow** [comment]
不需要上传，报错了？这个是动态 build 的

**Comment by nickyzhang-fe** [comment]
> 不需要上传，报错了？这个是动态 build 的

pnpm run start 时报错

![image](https://github.com/hlerenow/chameleon/assets/10348941/7854be7e-9c3a-4633-acd8-acd6243335ba)

**Comment by hlerenow** [comment]
参考: https://github.com/hlerenow/chameleon/blob/master/DEV_README.md

**Comment by hlerenow** [comment]
我使用的 mac, win 没跑过。你试试

**Comment by nickyzhang-fe** [comment]
> 我使用的 mac, win 没跑过。你试试

好的，晚上回去我用mac试一下
