### ISSUE TITLE
请问public下的的render.umd.js是从哪里来的

### ISSUE THREAD

**Issue by ZFzzz** [hlerenow/chameleon#4]
请问public下的的render.umd.js是从哪里来的呀，这个render.js主要是渲染哪一块 ，为什么不能通过import或者cdn引入呀

**Comment by ZFzzz** [comment]
![Uploading CE1D81FF-F1E4-4B8A-92B5-8383EBC2A446.png…]()

**Comment by hlerenow** [comment]
* render.umd.js 是 @chamn/render 的 umd 模式的 js 包，目前没有 cdn 地址, 所以是放在项目里面用相对路径引用的，如果有 cdn 地址是可以使用 cdn 地址的
* render 主要负责引擎界面中间的画布编辑区域的渲染，用于渲染真正的产出的页面内容
* 因为需要在 iframe 中加载 render 所以不能使用 import 直接引入

**Comment by ZFzzz** [comment]
请问大佬如果想接入第三方组件的话 是不是只能把第三方组件注册成CMaterialPropsType类型，这个类型里的setters没太明白是啥意思
![326AF919-E917-453D-8924-AD903179D353](https://user-images.githubusercontent.com/29327965/231968338-8bdf78cf-0117-4185-8eb0-8c5a455eb7ab.png)

**Comment by hlerenow** [comment]
- 这里是描述组件行为的物料，不会直接限制组件本身，这里的意思是 组件接受一个属性key 为 $$attributes,  描述 了它的接收的数据类型，setter 可以理解为一个 数据的输入组件（类似 input 组件）描述，表示我要用那个输入控件让 用户可以出入值。
- 对于第三方组件接入到这个编辑器 = 组件本身的 js 库 + 对组件库中所有的组件描述文件（组件物料），这个需要自行编写，按照编辑器的规则，最后注入到编辑器就可以使用。
- 目前我还在写对应的接入使用，后续可以关注下

**Comment by hlerenow** [comment]
组件和组件物料的关联就是 componentName， 这个需要在页面内唯一

**Comment by hlerenow** [comment]
已添加部分文档 https://hlerenow.github.io/chameleon/documents/
