### ISSUE TITLE
如何通过 setter 来控制组件 children 或设置 isContainer 选项？

### ISSUE THREAD

**Issue by StringKe** [hlerenow/chameleon#5]
```
<Button>text</Button>
<Button><Icon/></Button>
```

Button 的 children 可以是 text 也可以是拽拖进来的 组件。

**Comment by hlerenow** [comment]
不是很理解你的问题，能说描述详细一些吗？最好有截图。
场景：
如果你想在右侧面板输入文本，让文本作为子元素。同时又希望某些情况下作为一个可以被拖拽的容器，类似这样：
![image](https://user-images.githubusercontent.com/13299648/233837403-c6516660-9cb6-4140-a06e-93696d11d911.png)
![image](https://user-images.githubusercontent.com/13299648/233837429-e8880cbe-7810-4a5f-8eaf-26b44be56667.png)

只需要给组件本身添加，一些 key即可，只要组件不接受 children，组件就不能被拖元素到内部，但是内部可以同过 props 使用其他的 key 作为 children. 

一个组件可以被拖入 children 的前提是组件配置了 isContainer, 同时 组件支持读取外部传入的 children

**Comment by StringKe** [comment]
![CleanShot 2023-04-23 at 19 38 11@2x](https://user-images.githubusercontent.com/31089228/233837559-da5718fd-1989-4c52-a5d8-1331085d6733.png)

右侧这个开启容器，是通过什么控制的呢？

**Comment by hlerenow** [comment]
组件接收一个 isContainer 的 props， 如果为 true 就将 props 传入的 children
 丢弃掉，使用 props 中的 text 字段，反之依然
`
props: {
  isContainer: boolean,
  text: string
}
`

**Comment by StringKe** [comment]
那这个组件的 metadata 需要永远标记成 isContianer 为 true ？ 不是通过 isContianer 这个来控制组件是否允许被拽拖进元素么？

**Comment by hlerenow** [comment]
你可以理解为，metadata 中的一定要为true，这样engine 才会提供拖拽的方式去生成children，但是生成的children内容，你组件内部可以不使用，相当于组件本身可以间接的控制拖入的内容

**Comment by StringKe** [comment]
你说的方案我明白，但存在组件依旧可以被拽拖进去，会多出冗余的数据的问题。

目前较好的方式可能是同一个组件，导出两个名字一个标记 isContainer 一个不进行标记。

**Comment by hlerenow** [comment]
数据冗余可以通过model包提供的方法遍历节点做数据清理，这个之前有计划提供，现在生成的数据有的是开发中才需要的冗余字段，后面会提供清理方法。

**Comment by hlerenow** [comment]
为啥你不把text也作为一个组件呢？

**Comment by hlerenow** [comment]
为啥你不把text也作为一个组件呢？

**Comment by StringKe** [comment]
我可以将 text 作为一个组件传递，但这个组件会被允许继续通过拽拖的方式新增更多的内容。

**Comment by hlerenow** [comment]
那其实是一个text组件和其他组件并排就好了，不是一定要嵌套到text内部

**Comment by StringKe** [comment]
并排也是被允许添加，TextButton 就是不允许添加子元素，里面只能是文本。

其实这个更应该是这么个需求，针对同一个组件可以支持多份 metadata 定义。

**Comment by hlerenow** [comment]
可以通过自定义setter 实现，自定义 setter 内可以修改节点的信息，然后在判断拖拽的时候读取node 的 meta 和 物料的 meta 做合并，节点的 meta 优先级高，应该就可以实现你想要的功能。

**Comment by hlerenow** [comment]
0.0.12 已经支持

参考：https://github.com/hlerenow/chameleon/blob/master/packages/engine/src/_dev_/page/Editor/index.tsx#L197
```
            TestSetter: (props: any) => {
              useEffect(() => {
                console.log(props);
                const currentNode = props.setterContext.pluginCtx.engine.getActiveNode();
                currentNode.value.configure.isContainer = false;
                currentNode.value.children = [];
                currentNode.updateValue();
                console.log('🚀 ~ file: index.tsx:200 ~ pluginManager.customPlugin ~ currentNode:', currentNode);
              }, []);
              return <div>123</div>;
            },
          };
```

**Comment by StringKe** [comment]
我同步了新的代码，在我本地运行 engine 的时候左侧大纲树好像有影响到

**Comment by StringKe** [comment]
![CleanShot 2023-04-23 at 23 53 05@2x](https://user-images.githubusercontent.com/31089228/233850217-a139cd80-2880-4b06-b282-c03603963494.png)
